### ISSUE TITLE
2010s childhood recovered

### ISSUE THREAD

**Issue by uhwot** [wavetro/stickmen-2020#1]
so i messed around the .blend file with a hex editor and i managed to get it working enough that i could do "file > append" and import most of the stuff to a new file :)
the objects named "feet" and "Plastic" crash blender, while everything else seems to import properly

download: https://drive.google.com/drive/folders/1n7XFt6NkchiHl7WGgszsz8-4TOV8DFtf?usp=sharing
![it works! wow!](https://github.com/wavetro/stickmen-2020/assets/54753080/403e0698-7750-4e74-9137-aa33639c9ea7)

**Comment by wavetro** [comment]
HOLY SHIT YES I LOVE YOU!!! I didn't think anyone would be able to pull this off!! I'll use these to reconstruct the file and then credit you in the README once I push the new version. Thank you so so much!!!!!!!!
